      - name: perms => set filesystem permissions
        file: dest=/var/www/MISP/app/{{ item }} owner=www-data group=www-data mode=0750 recurse=yes
        sudo: yes
        with_items:
          - tmp
          - files
          - Config
          - Plugin/CakeResque/tmp/
        tags:
          - permissions

      - name: perms => set script to be executable
        file: dest=/var/www/MISP/app/Console/worker/start.sh mode=0750 group=www-data
        sudo: yes
        tags:
          - permissions
